language: go
go:
  - 1.0.3
  - 1.1.2
env:
  - GOARCH=amd64
  - GOARCH=386
install:
  - go get code.google.com/p/go.tools/go/vcs || true
  - "sed -i -e '26s/}/}\\nreturn nil, nil/' $HOME/gopath/src/code.google.com/p/go.tools/go/vcs/discovery.go"
  - go get github.com/kr/godep
script:
  - export PATH="$HOME/gopath/bin:$PATH"
  - ./test.sh
notifications:
  email: false
