language: go
go:
  - 1.0.3
  - 1.1.2
env:
  - GOARCH=amd64
  - GOARCH=386
install:
  - go get github.com/bmizerany/assert
  - go get github.com/bitly/go-nsq
  - go get github.com/bitly/go-hostpool
  - go get github.com/bitly/go-simplejson
script:
  - pushd $TRAVIS_BUILD_DIR
  - ./test.sh
  - popd
notifications:
  email: false
